# Generated by Django 5.2.9 on 2026-08-07 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_product_max_installments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Sessão')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP (anonimizado)')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('path', models.CharField(blank=True, max_length=300, verbose_name='Página de entrada')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Quando')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='metrics_vis_created_6b2433_idx'), models.Index(fields=['session_key', '-created_at'], name='metrics_vis_session_9f2550_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Sessão')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP (anonimizado)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Quando')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_views', to='catalog.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Visualização de produto',
                'verbose_name_plural': 'Visualizações de produtos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='metrics_pro_product_06a984_idx'), models.Index(fields=['-created_at'], name='metrics_pro_created_556167_idx')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Sessão')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP (anonimizado)')),
                ('source_path', models.CharField(blank=True, max_length=300, verbose_name='Página de origem')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Quando')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_clicks', to='catalog.product', verbose_name='Produto (se aplicável)')),
            ],
            options={
                'verbose_name': 'Clique no WhatsApp',
                'verbose_name_plural': 'Cliques no WhatsApp',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='metrics_wha_created_0107b1_idx'), models.Index(fields=['product', '-created_at'], name='metrics_wha_product_5c34e4_idx')],
            },
        ),
    ]
