# Generated by Django 5.0.9 on 2026-07-22 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Subtítulo')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Imagem')),
                ('link_url', models.CharField(blank=True, max_length=255, verbose_name='Link ao clicar (opcional)')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], unique=True, verbose_name='Dia da semana')),
                ('opens_at', models.TimeField(blank=True, null=True, verbose_name='Abre às')),
                ('closes_at', models.TimeField(blank=True, null=True, verbose_name='Fecha às')),
                ('closed', models.BooleanField(default=False, verbose_name='Fechado neste dia')),
            ],
            options={
                'verbose_name': 'Horário de funcionamento',
                'verbose_name_plural': 'Horários de funcionamento',
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sandra Ellen Modas', max_length=120, verbose_name='Nome da loja')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='Chamada curta')),
                ('about_text', models.TextField(blank=True, verbose_name="Texto 'Sobre'")),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Cidade/UF')),
                ('zip_code', models.CharField(blank=True, max_length=12, verbose_name='CEP')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('whatsapp_number', models.CharField(help_text='Ex: 557532662033', max_length=20, verbose_name='WhatsApp (só números, com DDI+DDD)')),
                ('whatsapp_default_message', models.CharField(default='Olá, gostaria de mais informações.', max_length=255, verbose_name='Mensagem padrão do WhatsApp')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('google_maps_embed_url', models.URLField(blank=True, verbose_name='URL do mapa incorporado (Google Maps embed)')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description padrão (SEO)')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Imagem Open Graph padrão')),
                ('google_analytics_id', models.CharField(blank=True, max_length=40, verbose_name='Google Analytics ID')),
                ('meta_pixel_id', models.CharField(blank=True, max_length=40, verbose_name='Meta Pixel ID')),
            ],
            options={
                'verbose_name': 'Informações da loja',
                'verbose_name_plural': 'Informações da loja',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Falha de login'), ('create', 'Criação'), ('update', 'Edição'), ('delete', 'Exclusão'), ('upload', 'Upload'), ('error', 'Erro')], max_length=20)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de auditoria',
                'verbose_name_plural': 'Logs de auditoria',
                'ordering': ['-created_at'],
            },
        ),
    ]
