# Generated by Django 5.2.9 on 2026-08-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_paymentmethod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='topbar_enabled',
            field=models.BooleanField(default=True, verbose_name='Exibir faixa no topo do site'),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='topbar_text',
            field=models.CharField(blank=True, default='Enviamos para todo o Brasil', help_text='Ex: Enviamos para todo o Brasil', max_length=200, verbose_name='Texto da faixa do topo'),
        ),
    ]
