# Generated by Django 5.0.9 on 2026-07-22 00:31

import apps.catalog.models
import apps.catalog.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', validators=[apps.catalog.validators.validate_image_file], verbose_name='Logo (opcional)')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug (URL amigável)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('short_description', models.CharField(max_length=255, verbose_name='Descrição curta')),
                ('full_description', models.TextField(blank=True, verbose_name='Descrição completa')),
                ('main_image', models.ImageField(upload_to=apps.catalog.models.product_image_upload_to, validators=[apps.catalog.validators.validate_image_file], verbose_name='Imagem principal')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('is_new', models.BooleanField(default=False, verbose_name='Novidade')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Mais vendido')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Title (SEO, opcional)')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description (SEO, opcional)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='Marca')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.catalog.models.product_image_upload_to, validators=[apps.catalog.validators.validate_image_file], verbose_name='Imagem')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo (acessibilidade)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Imagem da galeria',
                'verbose_name_plural': 'Imagens da galeria',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active', '-created_at'], name='catalog_pro_active_58dda1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='catalog_pro_slug_2b1eb6_idx'),
        ),
    ]
