# Generated by Django 5.0.9 on 2026-07-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_promotional_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(blank=True, help_text='Digite livremente, ex: P, M, G ou 36, 38, 40, 42.', max_length=100, verbose_name='Tamanhos disponíveis (opcional)'),
        ),
    ]
